# @package _group_
data_root_dir: /kaggle/working/lama_kaa/celeba-hq-dataset/
out_root_dir:  /kaggle/working/lama_kaa/experiments/
tb_dir:  /kaggle/working/lama_kaa/tb_logs/
pretrained_models:  /kaggle/working/lama_kaa/lama-main/
